blog/urls.py
from django.conf.urls import url
from django.core.urlresolvers import reverse

from .views import (PostList, post_detail, PostCreate)
urlpatterns = [
	url(r'^$', PostList.as_view(template_name='blog/post_list.html'), name='blog_post_list'),
	url(r'^(?P<year>\d{4})/'r'(?P<month>\d{1,2})/'r'(?P<slug>[\w\-]+)/$', post_detail, name='blog_post_detail'),
	url(r'^create/$', PostCreate.as_view(), name='blog_post_create'),
	]

organizer/urls.py
from django.conf.urls import url

from .views import (tag_list, tag_detail, startup_list, TagCreate, startup_list, StartupCreate, NewsLinkCreate)

urlpatterns = [
	url(r'^tag/$', tag_list, name='organizer_tag_list'),
	url(r'^tag/create/$', TagCreate.as_view(), name='organizer_tag_create'),
	url(r'^tag/(?P<slug>[\w\-]+)/$',
		tag_detail,
		name = 'organizer_tag_detail'),
	url(r'^startup/$', startup_list, name='organizer_startup_list'),
	url(r'^startup/create/$', StartupCreate.as_view(), name='organizer_startup_create'),
	url(r'^newslink/create/$', NewsLinkCreate.as_view(), name='organizer_newslink_create'),
	#url(r'^startup/(?P<slug>[\w\-]+)/$', startup_detail, name='organizer_startup_detail'),
	]

suorganizer/urls.py
from django.conf.urls import url, include
from django.contrib import admin
####################################
from organizer import urls as organizer_urls
from blog import urls as blog_urls
####################################
from .views import redirect_root
from blog.views import PostList

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', redirect_root),
    url(r'^', include(organizer_urls)),
    
    url(r'^blog/', include(blog_urls))
]

blog/models.py
from django.db import models
from organizer.models import Startup , Tag
from django.core.urlresolvers import reverse

# Create your models here.
class Post (models.Model):
    title = models.CharField(max_length=63)
    slug = models.SlugField(max_length=63,help_text='A lable for URL config', unique_for_month='pub_date' )
    text = models.TextField()
    pub_date = models.DateField('date published', auto_now_add=True)
    tags = models.ManyToManyField(Tag, related_name='blog_post')
    startups = models.ManyToManyField(Startup, related_name='blog_post')
    
    
    def get_absolute_url(self):
        return reverse('blog_post_detail', kwargs={'year':self.pub_date.year, 'month':self.pub_date.month, 'slug':self.slug})
    
    def __str__(self):
        return "{} on {}".format(self.title, self.pub_date.strftime('%Y-%m-%d'))

    class Meta:
        verbose_name = 'blog post'
        ordering = ['-pub_date', 'title']
        get_latest_by = 'pub_date'

organizer/models.py
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.

class Tag (models.Model):
    name = models.CharField(max_length=31, unique=True)
    slug = models.SlugField(max_length=31, unique=True, help_text='A label for config.')
    
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('organizer_tag_detail', args=(self.slug,))
    
    class Meta:
        ordering = ['name']
#####################################################################################################################
class Startup (models.Model):
    name = models.CharField(max_length=31, db_index = True)
    slug = models.SlugField(max_length=31, db_index=True, help_text ='A label for URL config')
    description = models.TextField()
    fuond_date = models.DateField('date founded')
    contact = models.EmailField()
    website = models.URLField(max_length = 255)
    tags = models.ManyToManyField(Tag)
    
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('organizer_startup_detail', kwargs={'slug':self.slug})
    
    class Meta:
        ordering = ['name']
        get_latest_by = 'founded_date'
#####################################################################################################################
class NewsLink (models.Model):
    name = models.CharField(max_length=31)
    pub_date = models.DateField('date published')
    link = models.URLField(max_length=255)
    startup = models.ForeignKey(Startup)
    def __str__(self):
        return "{}:{}".format(self.startup, self.title)
    class Meta:
        verbose_name = 'news article'
        ordering = ['-pub_date']
        get_latest_by = 'pub_date'

blog/forms.py
from django import forms

from .models import Post

class PostForm (forms.ModelForm):
	class Meta:
		model = Post
		fields = '__all__'
	
	def clean_slug(self):
		return self.cleaned_data['slug'].lower()

organizer/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import Tag, Startup, NewsLink


class SlugCleanMixin:
	def clean_slug(self):
		new_slug = (self.cleaned_data['slug'].lower())
		if new_slug =='create':
			raise ValidationError('slug may not be "create"')
		return new_slug

class NewsLinkForm (SlugCleanMixin, forms.ModelForm):
	class Meta:
		model = NewsLink
		fields = '__all__'

class StartupForm (SlugCleanMixin, forms.ModelForm):
	class Meta:
		model = Startup
		fields = '__all__'

class TagForm(SlugCleanMixin, forms.ModelForm):
	
	class Meta:
		model = Tag
		fields = '__all__'
	
	def clean_name(self):
		return self.cleaned_data['name'].lower()

blog/views.py
from django.shortcuts import (render, get_object_or_404, redirect)
from django.views.generic import View
from .models import Post
from .forms import PostForm

from django.views.decorators.http import require_http_methods


def post_list(request):
	return render(request, 'blog/post_list.html', {'post_list': post.objects.all()}) 
@require_http_methods(['HEAD', 'GET'])

def post_detail(request, year, month, slug):
	post =get_object_or_404(Post, pub_date__year=year, pub_date__month=month, slug=slug)
	return render(request, 'blog/post_detail.html', {'post':post})

class PostList (View):
	
	template_name = 'blog/post_list.html'
	
	def get (self, request):
		return render(request, self.template_name, {'post_list': Post.objects.all()})

class PostCreate (View):
	form_class = PostForm
	template_name = 'blog/post_form.html'

	def get(self, request):
		return render(request, self.template_name, {'form':self.form_class})

	def post(self, request):
		bound_form = self.form_class(request.POST)
		if bound_form.is_valid():
			new_post = bound_form.save()
			return redirect(new_post)
		else:
			return render(request, self.template_name, {'form':bound_form})

organizer/views.py
#from django.http.response import HttpResponse
from .models import Tag, Startup
#from django.template import loader, RequestContext
from django.shortcuts import (get_object_or_404, render, redirect)
from .forms import TagForm, StartupForm, NewsLinkForm
from django.views.generic import View
from .utils import ObjectCreateMixin

# def Tag_create(request):
#     if request.method == 'POST':
#         form = TagForm(request.POST)
#         if form.is_valid():
#             new_tag = form.save()
#             return redirect(new_tag)
#     else:
#         form = tag_form()
#         return render(request, 'organizer/tag_form.html', {'form':form})

class TagCreate (ObjectCreateMixin, View):
    form_class = TagForm
    template_name = 'organizer/tag_form.html'

class StartupCreate (ObjectCreateMixin, View):
    form_class = StartupForm
    template_name = 'organizer/startup_form.html'

class NewsLinkCreate (ObjectCreateMixin, View):
    form_class = NewsLinkForm
    template_name = 'organizer/newslink_form.html'

################################################################################################
def startup_list(request, slug):
    startup = get_object_or_404(Startup, slug__iexact=slug)
    return render(request, 'organizer/startup_list.html', {'startup_list':startup})

def tag_list (request):
    return render(request,'organizer/tag_list.html', {'tag_list':Tag.objects.all()})

def tag_detail(request, slug):
    tag = get_object_or_404(Tag, slug__iexact=slug)
    return render(request, 'organizer/tag_detail.html', {'tag':tag})

suorganizer/views.py
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse

def redirect_root(request):
	url_path = reverse('blog_post_list')
	return HttpResponseRedirect('/blog/')

blog/templates/blog/base_blog.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

blog/templates/blog/post_detail.html
<article>
    <header>
        <h2>{{post.title|title}}</h2>
        <p>
            written on
            <time datetime="{{post.pub_date|date:"Y-m-d" }}">
                {{post.pub_date|date:"l, F j, Y"}}
            </time>
        </p>
    </header>
    {{post.text|linebreaks}}
    {% if post.startups.all or post.tags.all %}
    <footer>
        {% if post.startups.all %}
        <section>
            <h3>Startup {{post.startups.count|pluralize }}</h3>
            <ul>
                {% for startups in post.startups.all %}
                <li><a href="{{startup.get_absolute_url}}">
                    {{srartup.name}}
                    </a></li>
                    {% endfor %}
            </ul>
        </section>
        {% endif %}
        
        {% if post.tag.all %}
        <section>
            <h3>Tag{{post.tags.count|pluralize}}</h3>
            <ul>
                {% for tag in post.tags.all %}
                <li><a href="{{post.get_absolute_url}}">
                    {{tag.name|title}}
                    </a></li>
                {% endfor %}
            </ul>
        </section>
        {% endif %}
    </footer>
    {% endif %}
</article>

blog/templates/blog/post_form.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{block.super}} - Create Blog Post
{% endblock %}

{% block content %}

<div>
	<div>
		<form
	  action="{% url 'blog_post_create' %}"
	  method="post">
	{% csrf_token %}
    {{ form.as_p}}
	<button type="submit">
		Create Blog Post</button>
        </form>
		
		
	</div>
</div>
{% endblock %}

blog/templates/blog/post_list.html
{% for post in post_list %}
<article>
    <header>
        <h2>
            <a href="{{post.get_absolute_url}}">
                {{post.title|title}}</a>
        </h2>
        <div>
            <a href="{% url 'blog_post_create' %}">
                Write New Post </a>
        </div>
        <p>
            written on:
            <time datetime="{{post.pub_date|date:'Y-m-d'}}">
                {{post.pub_date|date:"l, F j, Y" }}
            </time>
        </p>
    </header>
    <p>{{post.text|truncatewords:20}}</p>
    <p>
        <a href="{{post.get_absolute_url}}">
            read more &helllip;</a>
    </p>
</article>
{% empty %}
<p><em>no blog posts available</em></p>
{% endfor %}

organizer/templates/organizer/base_organizer.html
{% extends parent_template|default:"base.html" %}

organizer/templates/organizer/newslink_form.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{block.super}} - Link News Article to startup
{% endblock %}

{% block content %}

<div>
	<div>
		<form
	  action="{% url 'organizer_newslink_create' %}"
	  method="post">
	{% csrf_token %}
    {{ form.as_p}}
	<button type="submit">
		Link Article</button>
        </form>
		
		
	</div>
</div>
{% endblock %}

organizer/templates/organizer/srartup_detail.html
<article>

	<h2>{{startup.name}}</h2>
	<dl>
	<dt>Date Founded</dt>
	<dd>{{startup.founded_date|date:"F js,Y"}}</dd>
	<dt>Website</dt>8<dd>{{	startup.website	}}</dd>
	<dt>Contact</dt>
	<dd>{{	startup.contact	}}</dd>

	<dt>Tag{{startup.tags.count|pluralize}}</dt>
	{% fortag in startup.tags.all %}
	<dd><a	href="{{tag.get_absolute_url}}">
	{{tag.name|title}}
	</a></dd>
	{% endfor %}

	</dl>

	{{ startup.description|linebreaks }}

	{% if startup.newslink_set.all %}
	<section>
	<h3>Recent News</h3>
	<ul>
	{% for newslink	in startup.newslink_set.all %}
	<li>
	<a href="{{ newslink.link }}">
	{{ newslink.title|title	}}</a>
	</li>
	{% endfor %}
	</ul>
	<p>
		<a href="{% url 'organizer_newslink_create' %}">
			Add Article</a>
	</p>
	</section>
	{% endif %}

	{% if startup.blog_posts.all %}
	<section>
	<h3>Blog Post{{	startup.blog_posts.all|pluralize }}</h3>
	<ul>
	{% for post in startup.blog_posts.all %}
	<li>
	<a href="{{post.get_absolute_url}}">
	{{ post.title|title }}</a>
	</li>
	{% endfor %}
	</ul>
	</section>
	{% endif %}

	</article>

organizer/templates/organizer/startup_form.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{block.super}} - Create Startup
{% endblock %}

{% block content %}

<div>
	<div>
		<form
	  action="{% url 'organizer_startup_url' %}"
	  method="post">
	{% csrf_token %}
    {{ form.as_p}}
	<button type="submit">
		Create Startup</button>
        </form>
		
		
	</div>
</div>
{% endblock %}

organizer/templates/organizer/startup_list.html
{%	extends	parent_template|default:"organizer/base_organizer.html"	%}

{%	block title	%} 
{{ block.super }} - startups
{%	endblock %}

{% block content %}
<h2> Startup Links </h2>
<div>
    <a href="{% url 'organizer_startup_create' %}">
        Create New Startup</a>
</div>
<ul>
    {% for startup in startup_list %}
    <li>
        <a href="{{startup.get_absolute_url}}">
            {{srartup.name}}</a>
    </li>
    {% empty %}
    <li><em> no startups available </em></li>
    {% endfor %}
</ul>
{% endblock %}

organizer/templates/organizer/tag_confirm_delete.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{block.super}} - Delete Tag
{% endblock %}

{% block content %}

<div>
	<div>
		<form
	  action="{{tag.get_delete_url}}"
	  method="post">
	{% csrf_token %}
    <p>
		Are you sure you want to delete tag {{tag.name}}?
			</p>
			<a href="{{ tag.get_absolute_url }}">
				Cancel</a>
	<button type="submit">
		delete Tag</button>
        </form>
		
		
	</div>
</div>
{% endblock %}

organizer/templates/organizer/tag_detail.html
{% extends parent_template|default:"organizer/base_organizer.html" %}
{% block title %}
{{block.super}} - {{tag.name|title}}
{% endblock %}

{% if tag.startup_set.all %}
<section>
<h3>Startups{{tag.startup_set.count|pluralize}}</h3>
<p> Tag is asociated with {{tag.startup_set.count}} startup {{tag.startup_set.all|pluralize }} </p>
<ul>
{% for startup in tag.startup_set.all %}
<li><a href="{{startup.get_absolute_url}}">
{{startup.name}}
</a></li>
{%endfor%}
</ul>
</section>
{% else %}
<p>this tag is not related to any startups </p>
{% endif %}
{% if tag.blog_posts.all %}
<section>
<h3>Blog Posts{{tag.blog_posts.count|pluralize</h3>
<ul>
{% for post in tag.blog_posts.all %}
<li><a href="{{post.get_absolute_url}}">
{{post.title|title}}
</a></li>
{% endfor %}
</ul>
</section>
{% else %}
<p>this tag is not related to any blog posts </p>
{% endif %}
{% if not tag.startup_set.all and not tag.blog_posts.all %}
<p>this tag is not related to any content </p>
{% endif %}

organizer/templates/organizer/tag_form.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{ block.super }} - Create Tag
{% endblock %}

{% block content %}
  <form
      action="{% url 'organizer_tag_create' %}"
      method="post">
    {% csrf_token %}
    {{ form.non_field_errors }}
    {{ form.name.errors }}
    <p>
      <label for="id_name">Name:</label>
      {{ form.name }}
    </p>
    {{ form.slug.errors }}
    <p>
      <label for="id_slug">Slug:</label>
      {{ form.slug }}
      <span class="helptext">
        {{ form.slug.help_text }}
      </span>
    </p>
    <button type="submit">
      Create Tag</button>
  </form>
{% endblock %}

organizer/templates/organizer/tag_form_update.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{block.super}} - Update Tag
{% endblock %}

{% block content %}

<div>
	<div>
		<form
	  action="{{tag.get_update_url}}"
	  method="post">
	{% csrf_token %}
    {{form.as_p}}  
	<button type="submit">
		Update Tag</button>
        </form>
		
		
	</div>
</div>
{% endblock %}

organizer/templates/organizer/tag_list.html
	{% extends parent_template|default:"base.html" %}

{% block title %}
{{block.super}} - Tag List
{% endblock %}

{% block content %}
<h2>Tag List </h2>
<div>
	<a href="{% url 'organizer_tag_create' %}">
		Create New Tag</a>
</div>
<ul>
{% for tag in tag_list %}
<li>
<a href="{{tag.get_absolute_url}}">
{{ tag.name|title }}</a>
</li>
{% empty %}
<p><em> there are curently no tag available </em></p>
{% endfor %}
</ul>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>
            {% block title %}
            Startup Organizer
            {% endblock %}
        </title>
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="viewport" content="width=devise-width, initial-scale=1">
        <!--[if IE]><script src="http://html5shiv.googlecode.com/svn/trunk/html5.js">
        </script><![endif]-->
    </head>
    <body>
        <div><!--container-->
        <header>
            <h1>Startup Organizer</h1>
        </header>
        <main>
            {% block content %}
            this is defualt content
            {% endblock %}
        </main>
        </div><!--container-->
        <nav>
            <ul>
                <li>
                    <a href="{% url 'blog_post_list' %}">
                        Blog</a></li>
                <li>
                    <a href="{% url 'organizer_startup_list' %}">
                        Startups</a></li>
                <li>
                    <a href="{% url 'organizer_tag_list' %}">
                        Tags</a></li>
            </ul>
        </nav>

        <footer>
            <p>
                &copy; 2015
                <a href="https://AndrewsForge.com/">
                Django Unleashed</a>
            </p>
        </footer>
    </body>
</html>